# Generated by Django 2.2.19 on 2022-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220914_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Для загрузки изображения нажмите на "Выбрать файл"', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
